---
title: "Lab5_KatieTumang"
author: "Katie Tumang"
date: "September 23, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

```{r}
Confirmed_State_6_13 <- read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/06-13-2020.csv")) %>%
  filter (Country_Region == "US") %>% 
  group_by(Province_State, Country_Region) %>% 
  summarise(Confirmed = sum(Confirmed)) 
```


```{r}
str(Confirmed_State_6_13)
```

```{r}
Confirmed_State_9_13 <-   read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/09-13-2020.csv")) %>% 
  filter (Country_Region == "US") %>% 
  group_by(Province_State, Country_Region) %>% 
  summarize(Confirmed = sum(Confirmed))
```

```{r}
str(Confirmed_State_9_13)
```

```{r}
setdiff(Confirmed_State_9_13$Province_State, Confirmed_State_6_13$Province_State)
```

```{r}
Confirmed_State_9_13 <- Confirmed_State_9_13 %>% 
  filter(Province_State !="Recovered")
```

```{r}
Confirmed_State_6_13_9_13_joined <- full_join(Confirmed_State_6_13,
    Confirmed_State_9_13, by = c("Province_State"))
head(Confirmed_State_6_13_9_13_joined)
```


```{r}
tail(Confirmed_State_6_13_9_13_joined, 5)
```

```{r}
Confirmed_State_6_13_9_13_joined <- full_join(Confirmed_State_6_13,
  Confirmed_State_6_13, by = c("Province_State")) %>% 
  rename(Confirmed_6_13_2020 = "Confirmed.x", Confirmed_9_13_2020 = "Confirmed.y") %>%
  select(-Country_Region.x, -Country_Region.y) %>% 
  replace_na(list(Confirmed_6_13_2020 = 0))
head(Confirmed_State_6_13_9_13_joined)
```

```{r}
which(is.na(Confirmed_State_6_13_9_13_joined))
```

### Switching between wide and long table formats

```{r}
Confirmed_State_6_13_9_13_joined_long <- Confirmed_State_6_13_9_13_joined %>% 
  pivot_longer(-c(Province_State),
               names_to = "Date", values_to = "Confirmed")
```

```{r, fig.width= 5, fig.height= 15}
Confirmed_joined_long_plot <- ggplot(Confirmed_State_6_13_9_13_joined_long, aes(x = Confirmed, y = Province_State)) +
  geom_col(aes(fill = Date, color = Date))
```

```{r, fig.width=10, fig.height= 15}
print(Confirmed_joined_long_plot + ggtitle("Figure 1. Confirmed COVID-19 cases in the US") + labs(y="Province/state", x = "Confirmed cases"))
```


### Working with time series data
#### Data Wrangling

```{r}
download.file(url="https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv", 
               destfile = "data/time_series_covid19_confirmed_global.csv")
```

```{r}
time_series_confirmed <-  read_csv("data/time_series_covid19_confirmed_global.csv")%>%
  rename(Province_State = "Province/State", Country_Region = "Country/Region")
```

```{r}
head(time_series_confirmed)
```

```{r}
time_series_confirmed_long <- time_series_confirmed %>%
  pivot_longer(-c(Province_State, Country_Region, Lat, Long),
                names_to = "Date", values_to = "Confirmed")
```

```{r}
head(time_series_confirmed_long)
```

```{r}
download.file(url="https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv", 
               destfile = "data/time_series_covid19_deaths_global.csv")
```

```{r}
time_series_deaths <- read_csv("data/time_series_covid19_deaths_global.csv") %>%
  rename(Province_State = "Province/State", Country_Region = "Country/Region")
```

```{r}
time_series_deaths_long <- time_series_deaths %>% 
  pivot_longer(-c(Province_State, Country_Region, Lat, Long),
                  names_to = "Date", values_to = "Deaths")
head(time_series_deaths_long)
```

#### Exercise 4

```{r}
time_series_deaths_long_plot <- time_series_deaths_long %>% 
 group_by(Country_Region) %>% 
  summarise(Deaths = sum(Deaths)) %>%
  ggplot(aes(x = Date, y = Deaths)) +
  geom_line() +
  ggtitle("Confirmed COVID-19 deaths worldwide")
```

#### Joining the time series tables

```{r}
time_series_confirmed_long <- time_series_confirmed_long %>% 
  unite(Key, Province_State, Country_Region, Date, sep = ".", remove = FALSE)
head(time_series_confirmed_long)
```

```{r}
time_series_deaths_long <- time_series_deaths_long %>% 
  unite(Key, Province_State, Country_Region, Date, sep = ".") %>% 
  select(Key, Deaths)
```

```{r}
time_series_long_joined <- full_join(time_series_confirmed_long, time_series_deaths_long, by = c("Key")) %>% 
  select(-Key)
head(time_series_long_joined)
```

```{r}
which(is.na(time_series_long_joined$Confirmed))
```

```{r}
which(is.na(time_series_long_joined$Deaths))
```

#### Exercise 5

```{r}
time_series_joined_ex5 <- time_series_long_joined %>% 
  filter (Country_Region == "US") %>% 
  drop_na(Deaths, Confirmed) %>% 
  mutate(Deaths_confirmed = Deaths / Confirmed)
str(time_series_joined_ex5)
```

#### Exercise 6

```{r}
time_series_joined_ex5 %>% 
  group_by(Country_Region,Date) %>% 
  filter (Country_Region == "US") %>% 
  ggplot(aes(x = Date, y = Deaths_confirmed))+
  geom_point() +
  geom_line() +
  ggtitle("US COVID-19 deaths/confirmed cases per day")
```

```{r}
library(lubridate)
```

```{r}
time_series_long_joined$Date <- mdy(time_series_long_joined$Date)
```

#### Exercise 7

```{r}
library(DT)
```

```{r, fig.height = 10, fig.width = 15}
time_series_long_joined %>% 
  group_by(Country_Region) %>% 
  summarize(Deaths = sum(Deaths, na.rm = TRUE)) %>% 
  slice_max(Deaths, n = 10) %>% 
  arrange(desc(Deaths))
datatable(time_series_long_joined)
```

```{r}
time_series_long_joined %>% 
  filter(Country_Region %in% c("US", "Brazil", "United Kingdom", "Italy", "Mexico", "France", "Spain", "India", "Iran", "Peru")) %>%
  ggplot(aes(x = Date, y = Deaths, fill = Country_Region, color = Country_Region)) +
  geom_point() +
  geom_line() +
  ggtitle("Top 10 Countries with COVID-19-related Deaths")
```


```{r}
time_series_long_joined_counts <- time_series_long_joined %>% 
  pivot_longer(-c(Province_State, Country_Region, Lat, Long, Date),
               names_to = "Report_Type", values_to = "Counts")
head(time_series_long_joined_counts)
```

#### Making Graphs from time series data

```{r}
time_series_long_joined %>% 
  group_by(Country_Region,Date) %>% 
  summarise_at(c("Confirmed", "Deaths"), sum) %>% 
  filter (Country_Region == "US") %>% 
  ggplot(aes(x = Date, y = Deaths))+
  geom_point() +
  geom_line() +
  ggtitle("US COVID-19 Deaths")
```

```{r}
time_series_long_joined %>% 
  group_by(Country_Region,Date) %>% 
  summarise_at(c("Confirmed", "Deaths"), sum) %>%
  filter (Country_Region %in% c("China","Japan", "Korea, South","Italy","Spain","US")) %>% 
  ggplot(aes(x = Date, y = Deaths)) +
  geom_point() +
  geom_line() +
  ggtitle("COVID-19 Deaths") +
  facet_wrap(~Country_Region, ncol=2, scales="free_y")
```

```{r}
time_series_long_joined %>% 
  group_by(Country_Region,Date) %>% 
  summarise_at(c("Confirmed", "Deaths"), sum) %>% 
  filter (Country_Region %in% c("China","France","Italy","Korea, South","US")) %>% 
  ggplot(aes(x = Date, y = Deaths, color = Country_Region)) +
  geom_point() +
  geom_line() +
  ggtitle("COVID-19 Deaths")
```

```{r}
time_series_long_joined_counts %>% 
  group_by(Country_Region, Report_Type, Date) %>% 
  summarise(Counts = sum(Counts)) %>% 
  filter (Country_Region == "US") %>% 
  ggplot(aes(x = Date, y = log2(Counts), fill = Report_Type, color = Report_Type)) +
           geom_point() +
           geom_line() +
           ggtitle("US COVID-19 Cases")
```
