---
title: "Lab9A_KatieTumang"
author: "Katie Tumang"
date: "11/14/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Control structures

### Conditional statements

```{r}
x <- runif(1, 0, 100)
if(x > 36) {
        y <- 1
} else {
        y <- 0
}
```


```{r}
x <- runif(1, 0, 100)
if(x > 50) {
        print("likely")
} else if(x >= 98) {
        print("definitely")
} else if(x == 50) {
        print("maybe!")
} else {
        print("unlikely")
}
```

### for Loops

```{r}
for(i in 1:6) {
        print(i)
}
```

```{r}
x <- c("first point","second point","troisieme")
for(i in 1:3) {
        print(x[i])  
}
```

```{r}
x <- c("first point","second point","troisieme","quatrieme")
for(i in seq_along(x)) {   
        print(x[i])
}
```

```{r}
x <- c("1998","1999","2001","2003")
for(year in x) {
        print(paste("I was born in",year))
}
```

```{r}
for(i in 1:2) print(x[i])
```

### Nested for loops

```{r}
x <- matrix(1:6, 2, 9)
for(i in seq_len(nrow(x))) {
        for(j in seq_len(ncol(x))) {
                print(x[i, j])
        }   
}
```

### while Loops

```{r}
count <- 39
while(count > 30) {
        print(count)
        count <- count - 3
}
```

```{r}
z <- 26
set.seed(1)
while(z >= 20 && z <= 30) {
        coin <- rbinom(1, 1, 0.5)
        
        if(coin == 1) {
                z <- z + 1
        } else {
                z <- z - 1
        } 
}
print(z)
```

## Functions

```{r}
f <- function() {
        cat("Hello!\nGoodbye!\nHello again!")
}
f() 
```

```{r}
f <- function(num) {
        for(i in seq_len(num)) {
                cat("Six\n")
        }
}
f(6)
```

```{r}
f <- function() {
        print(paste("hello"))
}
f()
```

```{r}
f <- function(num = 1) {
        hello <- "hello!\n"
        for(i in seq_len(num)) {
                cat(hello)
        }
        chars <- nchar(hello) * num
        chars
}
f()
meaningoflife <- f(9)
print(meaningoflife)
f(num = 5)
```


